-- 저장하는 것은 공급사 코드와 내부 식별자의 매핑뿐이다.
-- 요금·재고의 원본은 외부에 있으므로 저장하지 않는다. (README §저장 정책)
--
-- 이름·최대 수용 인원도 두지 않는다. 그 값들은 재고·요금 응답에 매번 실려 오므로
-- 여기에 복사해 두면 같은 값의 출처가 둘이 되고, 언젠가 어긋난다.
--
-- 매 기동마다 실행되므로 (spring.sql.init.mode=always) if not exists 로 둔다.

-- 숙소 매핑: (공급사, 공급사 숙소 코드) → 내부 숙소 식별자
create table if not exists property_mapping (
    id                     bigint generated by default as identity primary key,
    supplier               varchar(16) not null,
    supplier_property_code varchar(64) not null,
    -- 이 제약이 "같은 공급사 상품은 언제 조회해도 같은 내부 식별자로 돌아온다"를 보장하는 장치다.
    constraint uq_property_mapping unique (supplier, supplier_property_code)
);

-- 객실 타입 매핑: (공급사, 공급사 숙소 코드, 공급사 객실 타입 코드) → 내부 객실 타입 식별자
--
-- 객실 타입 코드는 해당 숙소 안에서만 유일하다. 다른 숙소에 같은 코드가 존재할 수 있으므로
-- 키에 숙소 코드가 함께 들어간다. 부모를 property_mapping.id 로 참조하지 않고 자연키
-- 두 컬럼으로 들고 있는 것은, 정규화할 때 조인 없이 세 값으로 바로 찾기 위해서다.
create table if not exists room_type_mapping (
    id                      bigint generated by default as identity primary key,
    supplier                varchar(16) not null,
    supplier_property_code  varchar(64) not null,
    supplier_room_type_code varchar(64) not null,
    constraint uq_room_type_mapping unique (supplier, supplier_property_code, supplier_room_type_code)
);
